services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healthdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/healthdb
    depends_on:
      - db

volumes:
  db_data:
